CREATE TABLE users (
id int unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'ユーザID',
name varchar(255) NOT NULL COMMENT 'ユーザ名',
email varchar(255) NOT NULL UNIQUE COMMENT 'ユーザ名',
password varchar(255) NOT NULL COMMENT 'パスワード',
create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時'
);
CREATE TABLE posts (
id int unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '投稿ID',
user_id int unsigned NOT NULL COMMENT 'ユーザID',
text text NOT NULL COMMENT '投稿テキスト',
create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日時',
FOREIGN KEY user_id REFERENCES users(id)
);
