version: '3'

services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    tty: true
    environment:
      - DSN=mysql:host=db;dbname=test;
      - DB_USER=root
      - DB_PASSWORD=root
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test